---
repo: Waishnav/waishnav.github.io
media_path: /public
collections:
  - name: Blogs
    git_path: /src/content/blog
    metadata_schema:
      - name: title
        type: title
        required: true
---
# GitCMS Configuration File
> [!WARNING]
> This is autogenerated configutation file by [GitCMS](https://gitcms.blog). Don't edit it on your own, edit it **only** using GitCMS UI
